
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file DieType.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using Agile.Entities.Validation;
#endregion

namespace Agile.Entities
{
	///<summary>
	/// An object representation of the 'tblDIEType' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class DieTypeBase : EntityBase, IDieType, IEntityId<DieTypeKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private DieTypeEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private DieTypeEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private DieTypeEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<DieType> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event DieTypeEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event DieTypeEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="DieTypeBase"/> instance.
		///</summary>
		public DieTypeBase()
		{
			this.entityData = new DieTypeEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="DieTypeBase"/> instance.
		///</summary>
		///<param name="_initial"></param>
		///<param name="_dieTypeName"></param>
		///<param name="_description"></param>
		///<param name="_isDefault"></param>
		///<param name="_selected"></param>
		///<param name="_active"></param>
		///<param name="_order"></param>
		///<param name="_projectId"></param>
		public DieTypeBase(System.String _initial, System.String _dieTypeName, System.String _description, 
			System.Boolean? _isDefault, System.Boolean? _selected, System.Boolean? _active, System.Int32? _order, 
			System.Int32? _projectId)
		{
			this.entityData = new DieTypeEntityData();
			this.backupData = null;

			this.Initial = _initial;
			this.DieTypeName = _dieTypeName;
			this.Description = _description;
			this.IsDefault = _isDefault;
			this.Selected = _selected;
			this.Active = _active;
			this.Order = _order;
			this.ProjectId = _projectId;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="DieType"/> instance.
		///</summary>
		///<param name="_initial"></param>
		///<param name="_dieTypeName"></param>
		///<param name="_description"></param>
		///<param name="_isDefault"></param>
		///<param name="_selected"></param>
		///<param name="_active"></param>
		///<param name="_order"></param>
		///<param name="_projectId"></param>
		public static DieType CreateDieType(System.String _initial, System.String _dieTypeName, System.String _description, 
			System.Boolean? _isDefault, System.Boolean? _selected, System.Boolean? _active, System.Int32? _order, 
			System.Int32? _projectId)
		{
			DieType newDieType = new DieType();
			newDieType.Initial = _initial;
			newDieType.DieTypeName = _dieTypeName;
			newDieType.Description = _description;
			newDieType.IsDefault = _isDefault;
			newDieType.Selected = _selected;
			newDieType.Active = _active;
			newDieType.Order = _order;
			newDieType.ProjectId = _projectId;
			return newDieType;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the DieTypeId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 DieTypeId
		{
			get
			{
				return this.entityData.DieTypeId; 
			}
			
			set
			{
				if (this.entityData.DieTypeId == value)
					return;
					
				OnColumnChanging(DieTypeColumn.DieTypeId, this.entityData.DieTypeId);
				this.entityData.DieTypeId = value;
				this.EntityId.DieTypeId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieTypeColumn.DieTypeId, this.entityData.DieTypeId);
				OnPropertyChanged("DieTypeId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Initial property. 
		///		
		/// </summary>
		/// <value>This type is char.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 10)]
		public virtual System.String Initial
		{
			get
			{
				return this.entityData.Initial; 
			}
			
			set
			{
				if (this.entityData.Initial == value)
					return;
					
				OnColumnChanging(DieTypeColumn.Initial, this.entityData.Initial);
				this.entityData.Initial = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieTypeColumn.Initial, this.entityData.Initial);
				OnPropertyChanged("Initial");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the DieTypeName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 250)]
		public virtual System.String DieTypeName
		{
			get
			{
				return this.entityData.DieTypeName; 
			}
			
			set
			{
				if (this.entityData.DieTypeName == value)
					return;
					
				OnColumnChanging(DieTypeColumn.DieTypeName, this.entityData.DieTypeName);
				this.entityData.DieTypeName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieTypeColumn.DieTypeName, this.entityData.DieTypeName);
				OnPropertyChanged("DieTypeName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Description property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 4000)]
		public virtual System.String Description
		{
			get
			{
				return this.entityData.Description; 
			}
			
			set
			{
				if (this.entityData.Description == value)
					return;
					
				OnColumnChanging(DieTypeColumn.Description, this.entityData.Description);
				this.entityData.Description = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieTypeColumn.Description, this.entityData.Description);
				OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the IsDefault property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return false. It is up to the developer
		/// to check the value of IsIsDefaultNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? IsDefault
		{
			get
			{
				return this.entityData.IsDefault; 
			}
			
			set
			{
				if (this.entityData.IsDefault == value)
					return;
					
				OnColumnChanging(DieTypeColumn.IsDefault, this.entityData.IsDefault);
				this.entityData.IsDefault = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieTypeColumn.IsDefault, this.entityData.IsDefault);
				OnPropertyChanged("IsDefault");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Selected property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return false. It is up to the developer
		/// to check the value of IsSelectedNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? Selected
		{
			get
			{
				return this.entityData.Selected; 
			}
			
			set
			{
				if (this.entityData.Selected == value)
					return;
					
				OnColumnChanging(DieTypeColumn.Selected, this.entityData.Selected);
				this.entityData.Selected = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieTypeColumn.Selected, this.entityData.Selected);
				OnPropertyChanged("Selected");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Active property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return false. It is up to the developer
		/// to check the value of IsActiveNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? Active
		{
			get
			{
				return this.entityData.Active; 
			}
			
			set
			{
				if (this.entityData.Active == value)
					return;
					
				OnColumnChanging(DieTypeColumn.Active, this.entityData.Active);
				this.entityData.Active = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieTypeColumn.Active, this.entityData.Active);
				OnPropertyChanged("Active");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Order property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsOrderNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? Order
		{
			get
			{
				return this.entityData.Order; 
			}
			
			set
			{
				if (this.entityData.Order == value)
					return;
					
				OnColumnChanging(DieTypeColumn.Order, this.entityData.Order);
				this.entityData.Order = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieTypeColumn.Order, this.entityData.Order);
				OnPropertyChanged("Order");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ProjectId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsProjectIdNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? ProjectId
		{
			get
			{
				return this.entityData.ProjectId; 
			}
			
			set
			{
				if (this.entityData.ProjectId == value)
					return;
					
				OnColumnChanging(DieTypeColumn.ProjectId, this.entityData.ProjectId);
				this.entityData.ProjectId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(DieTypeColumn.ProjectId, this.entityData.ProjectId);
				OnPropertyChanged("ProjectId");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of DieRequest objects
		///	which are related to this object through the relation FK_tblDIERequest_tblDIEType
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<DieRequest> DieRequestCollection
		{
			get { return entityData.DieRequestCollection; }
			set { entityData.DieRequestCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Initial", "Initial", 10));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("DieTypeName", "Die Type Name", 250));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Description", "Description", 4000));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tblDIEType"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"DIETypeID", "Initial", "DIETypeName", "Description", "IsDefault", "Selected", "Active", "Order", "ProjectID"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as DieTypeEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (DieType) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<DieType>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as DieType);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed DieType Entity 
		///</summary>
		protected virtual DieType Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			DieType copy = new DieType();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.DieTypeId = this.DieTypeId;
				copy.Initial = this.Initial;
				copy.DieTypeName = this.DieTypeName;
				copy.Description = this.Description;
				copy.IsDefault = this.IsDefault;
				copy.Selected = this.Selected;
				copy.Active = this.Active;
				copy.Order = this.Order;
				copy.ProjectId = this.ProjectId;
			
		
			//deep copy nested objects
			copy.DieRequestCollection = (TList<DieRequest>) MakeCopyOf(this.DieRequestCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed DieType Entity 
		///</summary>
		public virtual DieType Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed DieType Entity which is a deep copy of the current entity.
		///</summary>
		public virtual DieType DeepCopy()
		{
			return EntityHelper.Clone<DieType>(this as DieType);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as DieTypeEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new DieTypeEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as DieTypeEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(DieTypeColumn column)
		{
			switch(column)
			{
					case DieTypeColumn.DieTypeId:
					return entityData.DieTypeId != _originalData.DieTypeId;
					case DieTypeColumn.Initial:
					return entityData.Initial != _originalData.Initial;
					case DieTypeColumn.DieTypeName:
					return entityData.DieTypeName != _originalData.DieTypeName;
					case DieTypeColumn.Description:
					return entityData.Description != _originalData.Description;
					case DieTypeColumn.IsDefault:
					return entityData.IsDefault != _originalData.IsDefault;
					case DieTypeColumn.Selected:
					return entityData.Selected != _originalData.Selected;
					case DieTypeColumn.Active:
					return entityData.Active != _originalData.Active;
					case DieTypeColumn.Order:
					return entityData.Order != _originalData.Order;
					case DieTypeColumn.ProjectId:
					return entityData.ProjectId != _originalData.ProjectId;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< DieTypeColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.DieTypeId != _originalData.DieTypeId;
			result = result || entityData.Initial != _originalData.Initial;
			result = result || entityData.DieTypeName != _originalData.DieTypeName;
			result = result || entityData.Description != _originalData.Description;
			result = result || entityData.IsDefault != _originalData.IsDefault;
			result = result || entityData.Selected != _originalData.Selected;
			result = result || entityData.Active != _originalData.Active;
			result = result || entityData.Order != _originalData.Order;
			result = result || entityData.ProjectId != _originalData.ProjectId;
			return result;
		}	
		
		///<summary>
		///  Returns a DieType Entity with the original data.
		///</summary>
		public DieType GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateDieType(
				_originalData.Initial,
				_originalData.DieTypeName,
				_originalData.Description,
				_originalData.IsDefault,
				_originalData.Selected,
				_originalData.Active,
				_originalData.Order,
				_originalData.ProjectId
				);
				
			return (DieType)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="DieTypeBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is DieTypeBase)
				return ValueEquals(this, (DieTypeBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="DieTypeBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.DieTypeId.GetHashCode() ^ 
					((this.Initial == null) ? string.Empty : this.Initial.ToString()).GetHashCode() ^ 
					((this.DieTypeName == null) ? string.Empty : this.DieTypeName.ToString()).GetHashCode() ^ 
					((this.Description == null) ? string.Empty : this.Description.ToString()).GetHashCode() ^ 
					((this.IsDefault == null) ? string.Empty : this.IsDefault.ToString()).GetHashCode() ^ 
					((this.Selected == null) ? string.Empty : this.Selected.ToString()).GetHashCode() ^ 
					((this.Active == null) ? string.Empty : this.Active.ToString()).GetHashCode() ^ 
					((this.Order == null) ? string.Empty : this.Order.ToString()).GetHashCode() ^ 
					((this.ProjectId == null) ? string.Empty : this.ProjectId.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="DieTypeBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(DieTypeBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="DieTypeBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="DieTypeBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="DieTypeBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(DieTypeBase Object1, DieTypeBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.DieTypeId != Object2.DieTypeId)
				equal = false;
			if ( Object1.Initial != null && Object2.Initial != null )
			{
				if (Object1.Initial != Object2.Initial)
					equal = false;
			}
			else if (Object1.Initial == null ^ Object2.Initial == null )
			{
				equal = false;
			}
			if ( Object1.DieTypeName != null && Object2.DieTypeName != null )
			{
				if (Object1.DieTypeName != Object2.DieTypeName)
					equal = false;
			}
			else if (Object1.DieTypeName == null ^ Object2.DieTypeName == null )
			{
				equal = false;
			}
			if ( Object1.Description != null && Object2.Description != null )
			{
				if (Object1.Description != Object2.Description)
					equal = false;
			}
			else if (Object1.Description == null ^ Object2.Description == null )
			{
				equal = false;
			}
			if ( Object1.IsDefault != null && Object2.IsDefault != null )
			{
				if (Object1.IsDefault != Object2.IsDefault)
					equal = false;
			}
			else if (Object1.IsDefault == null ^ Object2.IsDefault == null )
			{
				equal = false;
			}
			if ( Object1.Selected != null && Object2.Selected != null )
			{
				if (Object1.Selected != Object2.Selected)
					equal = false;
			}
			else if (Object1.Selected == null ^ Object2.Selected == null )
			{
				equal = false;
			}
			if ( Object1.Active != null && Object2.Active != null )
			{
				if (Object1.Active != Object2.Active)
					equal = false;
			}
			else if (Object1.Active == null ^ Object2.Active == null )
			{
				equal = false;
			}
			if ( Object1.Order != null && Object2.Order != null )
			{
				if (Object1.Order != Object2.Order)
					equal = false;
			}
			else if (Object1.Order == null ^ Object2.Order == null )
			{
				equal = false;
			}
			if ( Object1.ProjectId != null && Object2.ProjectId != null )
			{
				if (Object1.ProjectId != Object2.ProjectId)
					equal = false;
			}
			else if (Object1.ProjectId == null ^ Object2.ProjectId == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((DieTypeBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static DieTypeComparer GetComparer()
        {
            return new DieTypeComparer();
        }
        */

        // Comparer delegates back to DieType
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(DieType rhs, DieTypeColumn which)
        {
            switch (which)
            {
            	
            	
            	case DieTypeColumn.DieTypeId:
            		return this.DieTypeId.CompareTo(rhs.DieTypeId);
            		
            		                 
            	
            	
            	case DieTypeColumn.Initial:
            		return this.Initial.CompareTo(rhs.Initial);
            		
            		                 
            	
            	
            	case DieTypeColumn.DieTypeName:
            		return this.DieTypeName.CompareTo(rhs.DieTypeName);
            		
            		                 
            	
            	
            	case DieTypeColumn.Description:
            		return this.Description.CompareTo(rhs.Description);
            		
            		                 
            	
            	
            	case DieTypeColumn.IsDefault:
            		return this.IsDefault.Value.CompareTo(rhs.IsDefault.Value);
            		
            		                 
            	
            	
            	case DieTypeColumn.Selected:
            		return this.Selected.Value.CompareTo(rhs.Selected.Value);
            		
            		                 
            	
            	
            	case DieTypeColumn.Active:
            		return this.Active.Value.CompareTo(rhs.Active.Value);
            		
            		                 
            	
            	
            	case DieTypeColumn.Order:
            		return this.Order.Value.CompareTo(rhs.Order.Value);
            		
            		                 
            	
            	
            	case DieTypeColumn.ProjectId:
            		return this.ProjectId.Value.CompareTo(rhs.ProjectId.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<DieTypeKey> Members
		
		// member variable for the EntityId property
		private DieTypeKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual DieTypeKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new DieTypeKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("DieType")
					.Append("|").Append( this.DieTypeId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{10}{9}- DieTypeId: {0}{9}- Initial: {1}{9}- DieTypeName: {2}{9}- Description: {3}{9}- IsDefault: {4}{9}- Selected: {5}{9}- Active: {6}{9}- Order: {7}{9}- ProjectId: {8}{9}{11}", 
				this.DieTypeId,
				(this.Initial == null) ? string.Empty : this.Initial.ToString(),
				(this.DieTypeName == null) ? string.Empty : this.DieTypeName.ToString(),
				(this.Description == null) ? string.Empty : this.Description.ToString(),
				(this.IsDefault == null) ? string.Empty : this.IsDefault.ToString(),
				(this.Selected == null) ? string.Empty : this.Selected.ToString(),
				(this.Active == null) ? string.Empty : this.Active.ToString(),
				(this.Order == null) ? string.Empty : this.Order.ToString(),
				(this.ProjectId == null) ? string.Empty : this.ProjectId.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tblDIEType' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class DieTypeEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// DIETypeID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblDIEType"</remarks>
		public System.Int32 DieTypeId;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// Initial : 
		/// </summary>
		public System.String		  Initial = null;
		
		/// <summary>
		/// DIETypeName : 
		/// </summary>
		public System.String		  DieTypeName = null;
		
		/// <summary>
		/// Description : 
		/// </summary>
		public System.String		  Description = null;
		
		/// <summary>
		/// IsDefault : 
		/// </summary>
		public System.Boolean?		  IsDefault = null;
		
		/// <summary>
		/// Selected : 
		/// </summary>
		public System.Boolean?		  Selected = null;
		
		/// <summary>
		/// Active : 
		/// </summary>
		public System.Boolean?		  Active = null;
		
		/// <summary>
		/// Order : 
		/// </summary>
		public System.Int32?		  Order = null;
		
		/// <summary>
		/// ProjectID : 
		/// </summary>
		public System.Int32?		  ProjectId = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region DieRequestCollection
		
		private TList<DieRequest> _dieRequestDieTypeId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _dieRequestDieTypeId
		/// </summary>
		
		public TList<DieRequest> DieRequestCollection
		{
			get
			{
				if (_dieRequestDieTypeId == null)
				{
				_dieRequestDieTypeId = new TList<DieRequest>();
				}
	
				return _dieRequestDieTypeId;
			}
			set { _dieRequestDieTypeId = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			DieTypeEntityData _tmp = new DieTypeEntityData();
						
			_tmp.DieTypeId = this.DieTypeId;
			
			_tmp.Initial = this.Initial;
			_tmp.DieTypeName = this.DieTypeName;
			_tmp.Description = this.Description;
			_tmp.IsDefault = this.IsDefault;
			_tmp.Selected = this.Selected;
			_tmp.Active = this.Active;
			_tmp.Order = this.Order;
			_tmp.ProjectId = this.ProjectId;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._dieRequestDieTypeId != null)
				_tmp.DieRequestCollection = (TList<DieRequest>) MakeCopyOf(this.DieRequestCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			DieTypeEntityData _tmp = new DieTypeEntityData();
						
			_tmp.DieTypeId = this.DieTypeId;
			
			_tmp.Initial = this.Initial;
			_tmp.DieTypeName = this.DieTypeName;
			_tmp.Description = this.Description;
			_tmp.IsDefault = this.IsDefault;
			_tmp.Selected = this.Selected;
			_tmp.Active = this.Active;
			_tmp.Order = this.Order;
			_tmp.ProjectId = this.ProjectId;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.DieRequestCollection = (TList<DieRequest>) MakeCopyOf(this.DieRequestCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DieTypeColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(DieTypeColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DieTypeColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(DieTypeColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DieTypeColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(DieTypeColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				DieTypeEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new DieTypeEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="DieTypeColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(DieTypeColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				DieTypeEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new DieTypeEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region DieTypeEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="DieType"/> object.
	/// </remarks>
	public class DieTypeEventArgs : System.EventArgs
	{
		private DieTypeColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the DieTypeEventArgs class.
		///</summary>
		public DieTypeEventArgs(DieTypeColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the DieTypeEventArgs class.
		///</summary>
		public DieTypeEventArgs(DieTypeColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The DieTypeColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="DieTypeColumn" />
		public DieTypeColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all DieType related events.
	///</summary>
	public delegate void DieTypeEventHandler(object sender, DieTypeEventArgs e);
	
	#region DieTypeComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class DieTypeComparer : System.Collections.Generic.IComparer<DieType>
	{
		DieTypeColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:DieTypeComparer"/> class.
        /// </summary>
		public DieTypeComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:DieTypeComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public DieTypeComparer(DieTypeColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="DieType"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="DieType"/> to compare.</param>
        /// <param name="b">The second <c>DieType</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(DieType a, DieType b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(DieType entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(DieType a, DieType b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public DieTypeColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region DieTypeKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="DieType"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class DieTypeKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the DieTypeKey class.
		/// </summary>
		public DieTypeKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the DieTypeKey class.
		/// </summary>
		public DieTypeKey(DieTypeBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.DieTypeId = entity.DieTypeId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the DieTypeKey class.
		/// </summary>
		public DieTypeKey(System.Int32 _dieTypeId)
		{
			#region Init Properties

			this.DieTypeId = _dieTypeId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private DieTypeBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public DieTypeBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the DieTypeId property
		private System.Int32 _dieTypeId;
		
		/// <summary>
		/// Gets or sets the DieTypeId property.
		/// </summary>
		public System.Int32 DieTypeId
		{
			get { return _dieTypeId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.DieTypeId = value;
				
				_dieTypeId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				DieTypeId = ( values["DieTypeId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["DieTypeId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("DieTypeId", DieTypeId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("DieTypeId: {0}{1}",
								DieTypeId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region DieTypeColumn Enum
	
	/// <summary>
	/// Enumerate the DieType columns.
	/// </summary>
	[Serializable]
	public enum DieTypeColumn : int
	{
		/// <summary>
		/// DieTypeId : 
		/// </summary>
		[EnumTextValue("DIETypeID")]
		[ColumnEnum("DIETypeID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		DieTypeId = 1,
		/// <summary>
		/// Initial : 
		/// </summary>
		[EnumTextValue("Initial")]
		[ColumnEnum("Initial", typeof(System.String), System.Data.DbType.AnsiStringFixedLength, false, false, true, 10)]
		Initial = 2,
		/// <summary>
		/// DieTypeName : 
		/// </summary>
		[EnumTextValue("DIETypeName")]
		[ColumnEnum("DIETypeName", typeof(System.String), System.Data.DbType.String, false, false, true, 250)]
		DieTypeName = 3,
		/// <summary>
		/// Description : 
		/// </summary>
		[EnumTextValue("Description")]
		[ColumnEnum("Description", typeof(System.String), System.Data.DbType.String, false, false, true, 4000)]
		Description = 4,
		/// <summary>
		/// IsDefault : 
		/// </summary>
		[EnumTextValue("IsDefault")]
		[ColumnEnum("IsDefault", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		IsDefault = 5,
		/// <summary>
		/// Selected : 
		/// </summary>
		[EnumTextValue("Selected")]
		[ColumnEnum("Selected", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		Selected = 6,
		/// <summary>
		/// Active : 
		/// </summary>
		[EnumTextValue("Active")]
		[ColumnEnum("Active", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		Active = 7,
		/// <summary>
		/// Order : 
		/// </summary>
		[EnumTextValue("Order")]
		[ColumnEnum("Order", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		Order = 8,
		/// <summary>
		/// ProjectId : 
		/// </summary>
		[EnumTextValue("ProjectID")]
		[ColumnEnum("ProjectID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		ProjectId = 9
	}//End enum

	#endregion DieTypeColumn Enum

} // end namespace
