using System;
using System.ComponentModel;

namespace Agile.Entities
{
	/// <summary>
	///		The data structure representation of the 'tblMileStole' table via interface.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	public interface IMileStole 
	{
		/// <summary>			
		/// MileStoleID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblMileStole"</remarks>
		System.Int32 MileStoleId { get; set; }
				
		
		
		/// <summary>
		/// MileStoleName : 
		/// </summary>
		System.String  MileStoleName  { get; set; }
		
		/// <summary>
		/// OriginalDueDate : 
		/// </summary>
		System.DateTime?  OriginalDueDate  { get; set; }
		
		/// <summary>
		/// RevisedDueDate : 
		/// </summary>
		System.DateTime?  RevisedDueDate  { get; set; }
		
		/// <summary>
		/// CompleteDate : 
		/// </summary>
		System.DateTime?  CompleteDate  { get; set; }
		
		/// <summary>
		/// Progress : 
		/// </summary>
		System.Double?  Progress  { get; set; }
		
		/// <summary>
		/// ProjectID : 
		/// </summary>
		System.Int32?  ProjectId  { get; set; }
		
		/// <summary>
		/// Enabled : 
		/// </summary>
		System.Boolean?  Enabled  { get; set; }
		
		/// <summary>
		/// MileStoleOrder : 
		/// </summary>
		System.Int32?  MileStoleOrder  { get; set; }
			
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		System.Object Clone();
		
		#region Data Properties


		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _dieRequestMilestoneId
		/// </summary>	
		TList<DieRequest> DieRequestCollection {  get;  set;}	

		#endregion Data Properties

	}
}


