
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file MileStole.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using Agile.Entities.Validation;
#endregion

namespace Agile.Entities
{
	///<summary>
	/// An object representation of the 'tblMileStole' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class MileStoleBase : EntityBase, IMileStole, IEntityId<MileStoleKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private MileStoleEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private MileStoleEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private MileStoleEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<MileStole> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event MileStoleEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event MileStoleEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="MileStoleBase"/> instance.
		///</summary>
		public MileStoleBase()
		{
			this.entityData = new MileStoleEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="MileStoleBase"/> instance.
		///</summary>
		///<param name="_mileStoleName"></param>
		///<param name="_originalDueDate"></param>
		///<param name="_revisedDueDate"></param>
		///<param name="_completeDate"></param>
		///<param name="_progress"></param>
		///<param name="_projectId"></param>
		///<param name="_enabled"></param>
		///<param name="_mileStoleOrder"></param>
		public MileStoleBase(System.String _mileStoleName, System.DateTime? _originalDueDate, 
			System.DateTime? _revisedDueDate, System.DateTime? _completeDate, System.Double? _progress, 
			System.Int32? _projectId, System.Boolean? _enabled, System.Int32? _mileStoleOrder)
		{
			this.entityData = new MileStoleEntityData();
			this.backupData = null;

			this.MileStoleName = _mileStoleName;
			this.OriginalDueDate = _originalDueDate;
			this.RevisedDueDate = _revisedDueDate;
			this.CompleteDate = _completeDate;
			this.Progress = _progress;
			this.ProjectId = _projectId;
			this.Enabled = _enabled;
			this.MileStoleOrder = _mileStoleOrder;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="MileStole"/> instance.
		///</summary>
		///<param name="_mileStoleName"></param>
		///<param name="_originalDueDate"></param>
		///<param name="_revisedDueDate"></param>
		///<param name="_completeDate"></param>
		///<param name="_progress"></param>
		///<param name="_projectId"></param>
		///<param name="_enabled"></param>
		///<param name="_mileStoleOrder"></param>
		public static MileStole CreateMileStole(System.String _mileStoleName, System.DateTime? _originalDueDate, 
			System.DateTime? _revisedDueDate, System.DateTime? _completeDate, System.Double? _progress, 
			System.Int32? _projectId, System.Boolean? _enabled, System.Int32? _mileStoleOrder)
		{
			MileStole newMileStole = new MileStole();
			newMileStole.MileStoleName = _mileStoleName;
			newMileStole.OriginalDueDate = _originalDueDate;
			newMileStole.RevisedDueDate = _revisedDueDate;
			newMileStole.CompleteDate = _completeDate;
			newMileStole.Progress = _progress;
			newMileStole.ProjectId = _projectId;
			newMileStole.Enabled = _enabled;
			newMileStole.MileStoleOrder = _mileStoleOrder;
			return newMileStole;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the MileStoleId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 MileStoleId
		{
			get
			{
				return this.entityData.MileStoleId; 
			}
			
			set
			{
				if (this.entityData.MileStoleId == value)
					return;
					
				OnColumnChanging(MileStoleColumn.MileStoleId, this.entityData.MileStoleId);
				this.entityData.MileStoleId = value;
				this.EntityId.MileStoleId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MileStoleColumn.MileStoleId, this.entityData.MileStoleId);
				OnPropertyChanged("MileStoleId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MileStoleName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 1000)]
		public virtual System.String MileStoleName
		{
			get
			{
				return this.entityData.MileStoleName; 
			}
			
			set
			{
				if (this.entityData.MileStoleName == value)
					return;
					
				OnColumnChanging(MileStoleColumn.MileStoleName, this.entityData.MileStoleName);
				this.entityData.MileStoleName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MileStoleColumn.MileStoleName, this.entityData.MileStoleName);
				OnPropertyChanged("MileStoleName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the OriginalDueDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsOriginalDueDateNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? OriginalDueDate
		{
			get
			{
				return this.entityData.OriginalDueDate; 
			}
			
			set
			{
				if (this.entityData.OriginalDueDate == value)
					return;
					
				OnColumnChanging(MileStoleColumn.OriginalDueDate, this.entityData.OriginalDueDate);
				this.entityData.OriginalDueDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MileStoleColumn.OriginalDueDate, this.entityData.OriginalDueDate);
				OnPropertyChanged("OriginalDueDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the RevisedDueDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsRevisedDueDateNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? RevisedDueDate
		{
			get
			{
				return this.entityData.RevisedDueDate; 
			}
			
			set
			{
				if (this.entityData.RevisedDueDate == value)
					return;
					
				OnColumnChanging(MileStoleColumn.RevisedDueDate, this.entityData.RevisedDueDate);
				this.entityData.RevisedDueDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MileStoleColumn.RevisedDueDate, this.entityData.RevisedDueDate);
				OnPropertyChanged("RevisedDueDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the CompleteDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return DateTime.MinValue. It is up to the developer
		/// to check the value of IsCompleteDateNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.DateTime? CompleteDate
		{
			get
			{
				return this.entityData.CompleteDate; 
			}
			
			set
			{
				if (this.entityData.CompleteDate == value)
					return;
					
				OnColumnChanging(MileStoleColumn.CompleteDate, this.entityData.CompleteDate);
				this.entityData.CompleteDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MileStoleColumn.CompleteDate, this.entityData.CompleteDate);
				OnPropertyChanged("CompleteDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Progress property. 
		///		
		/// </summary>
		/// <value>This type is float.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return 0.0f. It is up to the developer
		/// to check the value of IsProgressNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Double? Progress
		{
			get
			{
				return this.entityData.Progress; 
			}
			
			set
			{
				if (this.entityData.Progress == value)
					return;
					
				OnColumnChanging(MileStoleColumn.Progress, this.entityData.Progress);
				this.entityData.Progress = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MileStoleColumn.Progress, this.entityData.Progress);
				OnPropertyChanged("Progress");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ProjectId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsProjectIdNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? ProjectId
		{
			get
			{
				return this.entityData.ProjectId; 
			}
			
			set
			{
				if (this.entityData.ProjectId == value)
					return;
					
				OnColumnChanging(MileStoleColumn.ProjectId, this.entityData.ProjectId);
				this.entityData.ProjectId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MileStoleColumn.ProjectId, this.entityData.ProjectId);
				OnPropertyChanged("ProjectId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Enabled property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return false. It is up to the developer
		/// to check the value of IsEnabledNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? Enabled
		{
			get
			{
				return this.entityData.Enabled; 
			}
			
			set
			{
				if (this.entityData.Enabled == value)
					return;
					
				OnColumnChanging(MileStoleColumn.Enabled, this.entityData.Enabled);
				this.entityData.Enabled = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MileStoleColumn.Enabled, this.entityData.Enabled);
				OnPropertyChanged("Enabled");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the MileStoleOrder property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return (int)0. It is up to the developer
		/// to check the value of IsMileStoleOrderNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Int32? MileStoleOrder
		{
			get
			{
				return this.entityData.MileStoleOrder; 
			}
			
			set
			{
				if (this.entityData.MileStoleOrder == value)
					return;
					
				OnColumnChanging(MileStoleColumn.MileStoleOrder, this.entityData.MileStoleOrder);
				this.entityData.MileStoleOrder = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(MileStoleColumn.MileStoleOrder, this.entityData.MileStoleOrder);
				OnPropertyChanged("MileStoleOrder");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of DieRequest objects
		///	which are related to this object through the relation FK_tblDIERequest_tblMileStole
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<DieRequest> DieRequestCollection
		{
			get { return entityData.DieRequestCollection; }
			set { entityData.DieRequestCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("MileStoleName", "Mile Stole Name", 1000));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tblMileStole"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"MileStoleID", "MileStoleName", "OriginalDueDate", "RevisedDueDate", "CompleteDate", "Progress", "ProjectID", "Enabled", "MileStoleOrder"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as MileStoleEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (MileStole) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<MileStole>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as MileStole);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed MileStole Entity 
		///</summary>
		protected virtual MileStole Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			MileStole copy = new MileStole();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.MileStoleId = this.MileStoleId;
				copy.MileStoleName = this.MileStoleName;
				copy.OriginalDueDate = this.OriginalDueDate;
				copy.RevisedDueDate = this.RevisedDueDate;
				copy.CompleteDate = this.CompleteDate;
				copy.Progress = this.Progress;
				copy.ProjectId = this.ProjectId;
				copy.Enabled = this.Enabled;
				copy.MileStoleOrder = this.MileStoleOrder;
			
		
			//deep copy nested objects
			copy.DieRequestCollection = (TList<DieRequest>) MakeCopyOf(this.DieRequestCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed MileStole Entity 
		///</summary>
		public virtual MileStole Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed MileStole Entity which is a deep copy of the current entity.
		///</summary>
		public virtual MileStole DeepCopy()
		{
			return EntityHelper.Clone<MileStole>(this as MileStole);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as MileStoleEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new MileStoleEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as MileStoleEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(MileStoleColumn column)
		{
			switch(column)
			{
					case MileStoleColumn.MileStoleId:
					return entityData.MileStoleId != _originalData.MileStoleId;
					case MileStoleColumn.MileStoleName:
					return entityData.MileStoleName != _originalData.MileStoleName;
					case MileStoleColumn.OriginalDueDate:
					return entityData.OriginalDueDate != _originalData.OriginalDueDate;
					case MileStoleColumn.RevisedDueDate:
					return entityData.RevisedDueDate != _originalData.RevisedDueDate;
					case MileStoleColumn.CompleteDate:
					return entityData.CompleteDate != _originalData.CompleteDate;
					case MileStoleColumn.Progress:
					return entityData.Progress != _originalData.Progress;
					case MileStoleColumn.ProjectId:
					return entityData.ProjectId != _originalData.ProjectId;
					case MileStoleColumn.Enabled:
					return entityData.Enabled != _originalData.Enabled;
					case MileStoleColumn.MileStoleOrder:
					return entityData.MileStoleOrder != _originalData.MileStoleOrder;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< MileStoleColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.MileStoleId != _originalData.MileStoleId;
			result = result || entityData.MileStoleName != _originalData.MileStoleName;
			result = result || entityData.OriginalDueDate != _originalData.OriginalDueDate;
			result = result || entityData.RevisedDueDate != _originalData.RevisedDueDate;
			result = result || entityData.CompleteDate != _originalData.CompleteDate;
			result = result || entityData.Progress != _originalData.Progress;
			result = result || entityData.ProjectId != _originalData.ProjectId;
			result = result || entityData.Enabled != _originalData.Enabled;
			result = result || entityData.MileStoleOrder != _originalData.MileStoleOrder;
			return result;
		}	
		
		///<summary>
		///  Returns a MileStole Entity with the original data.
		///</summary>
		public MileStole GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateMileStole(
				_originalData.MileStoleName,
				_originalData.OriginalDueDate,
				_originalData.RevisedDueDate,
				_originalData.CompleteDate,
				_originalData.Progress,
				_originalData.ProjectId,
				_originalData.Enabled,
				_originalData.MileStoleOrder
				);
				
			return (MileStole)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="MileStoleBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is MileStoleBase)
				return ValueEquals(this, (MileStoleBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="MileStoleBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.MileStoleId.GetHashCode() ^ 
					((this.MileStoleName == null) ? string.Empty : this.MileStoleName.ToString()).GetHashCode() ^ 
					((this.OriginalDueDate == null) ? string.Empty : this.OriginalDueDate.ToString()).GetHashCode() ^ 
					((this.RevisedDueDate == null) ? string.Empty : this.RevisedDueDate.ToString()).GetHashCode() ^ 
					((this.CompleteDate == null) ? string.Empty : this.CompleteDate.ToString()).GetHashCode() ^ 
					((this.Progress == null) ? string.Empty : this.Progress.ToString()).GetHashCode() ^ 
					((this.ProjectId == null) ? string.Empty : this.ProjectId.ToString()).GetHashCode() ^ 
					((this.Enabled == null) ? string.Empty : this.Enabled.ToString()).GetHashCode() ^ 
					((this.MileStoleOrder == null) ? string.Empty : this.MileStoleOrder.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="MileStoleBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(MileStoleBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="MileStoleBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="MileStoleBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="MileStoleBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(MileStoleBase Object1, MileStoleBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.MileStoleId != Object2.MileStoleId)
				equal = false;
			if ( Object1.MileStoleName != null && Object2.MileStoleName != null )
			{
				if (Object1.MileStoleName != Object2.MileStoleName)
					equal = false;
			}
			else if (Object1.MileStoleName == null ^ Object2.MileStoleName == null )
			{
				equal = false;
			}
			if ( Object1.OriginalDueDate != null && Object2.OriginalDueDate != null )
			{
				if (Object1.OriginalDueDate != Object2.OriginalDueDate)
					equal = false;
			}
			else if (Object1.OriginalDueDate == null ^ Object2.OriginalDueDate == null )
			{
				equal = false;
			}
			if ( Object1.RevisedDueDate != null && Object2.RevisedDueDate != null )
			{
				if (Object1.RevisedDueDate != Object2.RevisedDueDate)
					equal = false;
			}
			else if (Object1.RevisedDueDate == null ^ Object2.RevisedDueDate == null )
			{
				equal = false;
			}
			if ( Object1.CompleteDate != null && Object2.CompleteDate != null )
			{
				if (Object1.CompleteDate != Object2.CompleteDate)
					equal = false;
			}
			else if (Object1.CompleteDate == null ^ Object2.CompleteDate == null )
			{
				equal = false;
			}
			if ( Object1.Progress != null && Object2.Progress != null )
			{
				if (Object1.Progress != Object2.Progress)
					equal = false;
			}
			else if (Object1.Progress == null ^ Object2.Progress == null )
			{
				equal = false;
			}
			if ( Object1.ProjectId != null && Object2.ProjectId != null )
			{
				if (Object1.ProjectId != Object2.ProjectId)
					equal = false;
			}
			else if (Object1.ProjectId == null ^ Object2.ProjectId == null )
			{
				equal = false;
			}
			if ( Object1.Enabled != null && Object2.Enabled != null )
			{
				if (Object1.Enabled != Object2.Enabled)
					equal = false;
			}
			else if (Object1.Enabled == null ^ Object2.Enabled == null )
			{
				equal = false;
			}
			if ( Object1.MileStoleOrder != null && Object2.MileStoleOrder != null )
			{
				if (Object1.MileStoleOrder != Object2.MileStoleOrder)
					equal = false;
			}
			else if (Object1.MileStoleOrder == null ^ Object2.MileStoleOrder == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((MileStoleBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static MileStoleComparer GetComparer()
        {
            return new MileStoleComparer();
        }
        */

        // Comparer delegates back to MileStole
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(MileStole rhs, MileStoleColumn which)
        {
            switch (which)
            {
            	
            	
            	case MileStoleColumn.MileStoleId:
            		return this.MileStoleId.CompareTo(rhs.MileStoleId);
            		
            		                 
            	
            	
            	case MileStoleColumn.MileStoleName:
            		return this.MileStoleName.CompareTo(rhs.MileStoleName);
            		
            		                 
            	
            	
            	case MileStoleColumn.OriginalDueDate:
            		return this.OriginalDueDate.Value.CompareTo(rhs.OriginalDueDate.Value);
            		
            		                 
            	
            	
            	case MileStoleColumn.RevisedDueDate:
            		return this.RevisedDueDate.Value.CompareTo(rhs.RevisedDueDate.Value);
            		
            		                 
            	
            	
            	case MileStoleColumn.CompleteDate:
            		return this.CompleteDate.Value.CompareTo(rhs.CompleteDate.Value);
            		
            		                 
            	
            	
            	case MileStoleColumn.Progress:
            		return this.Progress.Value.CompareTo(rhs.Progress.Value);
            		
            		                 
            	
            	
            	case MileStoleColumn.ProjectId:
            		return this.ProjectId.Value.CompareTo(rhs.ProjectId.Value);
            		
            		                 
            	
            	
            	case MileStoleColumn.Enabled:
            		return this.Enabled.Value.CompareTo(rhs.Enabled.Value);
            		
            		                 
            	
            	
            	case MileStoleColumn.MileStoleOrder:
            		return this.MileStoleOrder.Value.CompareTo(rhs.MileStoleOrder.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<MileStoleKey> Members
		
		// member variable for the EntityId property
		private MileStoleKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual MileStoleKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new MileStoleKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("MileStole")
					.Append("|").Append( this.MileStoleId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{10}{9}- MileStoleId: {0}{9}- MileStoleName: {1}{9}- OriginalDueDate: {2}{9}- RevisedDueDate: {3}{9}- CompleteDate: {4}{9}- Progress: {5}{9}- ProjectId: {6}{9}- Enabled: {7}{9}- MileStoleOrder: {8}{9}{11}", 
				this.MileStoleId,
				(this.MileStoleName == null) ? string.Empty : this.MileStoleName.ToString(),
				(this.OriginalDueDate == null) ? string.Empty : this.OriginalDueDate.ToString(),
				(this.RevisedDueDate == null) ? string.Empty : this.RevisedDueDate.ToString(),
				(this.CompleteDate == null) ? string.Empty : this.CompleteDate.ToString(),
				(this.Progress == null) ? string.Empty : this.Progress.ToString(),
				(this.ProjectId == null) ? string.Empty : this.ProjectId.ToString(),
				(this.Enabled == null) ? string.Empty : this.Enabled.ToString(),
				(this.MileStoleOrder == null) ? string.Empty : this.MileStoleOrder.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tblMileStole' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class MileStoleEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// MileStoleID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblMileStole"</remarks>
		public System.Int32 MileStoleId;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// MileStoleName : 
		/// </summary>
		public System.String		  MileStoleName = null;
		
		/// <summary>
		/// OriginalDueDate : 
		/// </summary>
		public System.DateTime?		  OriginalDueDate = null;
		
		/// <summary>
		/// RevisedDueDate : 
		/// </summary>
		public System.DateTime?		  RevisedDueDate = null;
		
		/// <summary>
		/// CompleteDate : 
		/// </summary>
		public System.DateTime?		  CompleteDate = null;
		
		/// <summary>
		/// Progress : 
		/// </summary>
		public System.Double?		  Progress = null;
		
		/// <summary>
		/// ProjectID : 
		/// </summary>
		public System.Int32?		  ProjectId = null;
		
		/// <summary>
		/// Enabled : 
		/// </summary>
		public System.Boolean?		  Enabled = null;
		
		/// <summary>
		/// MileStoleOrder : 
		/// </summary>
		public System.Int32?		  MileStoleOrder = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region DieRequestCollection
		
		private TList<DieRequest> _dieRequestMilestoneId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _dieRequestMilestoneId
		/// </summary>
		
		public TList<DieRequest> DieRequestCollection
		{
			get
			{
				if (_dieRequestMilestoneId == null)
				{
				_dieRequestMilestoneId = new TList<DieRequest>();
				}
	
				return _dieRequestMilestoneId;
			}
			set { _dieRequestMilestoneId = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			MileStoleEntityData _tmp = new MileStoleEntityData();
						
			_tmp.MileStoleId = this.MileStoleId;
			
			_tmp.MileStoleName = this.MileStoleName;
			_tmp.OriginalDueDate = this.OriginalDueDate;
			_tmp.RevisedDueDate = this.RevisedDueDate;
			_tmp.CompleteDate = this.CompleteDate;
			_tmp.Progress = this.Progress;
			_tmp.ProjectId = this.ProjectId;
			_tmp.Enabled = this.Enabled;
			_tmp.MileStoleOrder = this.MileStoleOrder;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._dieRequestMilestoneId != null)
				_tmp.DieRequestCollection = (TList<DieRequest>) MakeCopyOf(this.DieRequestCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			MileStoleEntityData _tmp = new MileStoleEntityData();
						
			_tmp.MileStoleId = this.MileStoleId;
			
			_tmp.MileStoleName = this.MileStoleName;
			_tmp.OriginalDueDate = this.OriginalDueDate;
			_tmp.RevisedDueDate = this.RevisedDueDate;
			_tmp.CompleteDate = this.CompleteDate;
			_tmp.Progress = this.Progress;
			_tmp.ProjectId = this.ProjectId;
			_tmp.Enabled = this.Enabled;
			_tmp.MileStoleOrder = this.MileStoleOrder;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.DieRequestCollection = (TList<DieRequest>) MakeCopyOf(this.DieRequestCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MileStoleColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(MileStoleColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MileStoleColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(MileStoleColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MileStoleColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(MileStoleColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				MileStoleEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new MileStoleEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="MileStoleColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(MileStoleColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				MileStoleEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new MileStoleEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region MileStoleEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="MileStole"/> object.
	/// </remarks>
	public class MileStoleEventArgs : System.EventArgs
	{
		private MileStoleColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the MileStoleEventArgs class.
		///</summary>
		public MileStoleEventArgs(MileStoleColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the MileStoleEventArgs class.
		///</summary>
		public MileStoleEventArgs(MileStoleColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The MileStoleColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="MileStoleColumn" />
		public MileStoleColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all MileStole related events.
	///</summary>
	public delegate void MileStoleEventHandler(object sender, MileStoleEventArgs e);
	
	#region MileStoleComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class MileStoleComparer : System.Collections.Generic.IComparer<MileStole>
	{
		MileStoleColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:MileStoleComparer"/> class.
        /// </summary>
		public MileStoleComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:MileStoleComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public MileStoleComparer(MileStoleColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="MileStole"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="MileStole"/> to compare.</param>
        /// <param name="b">The second <c>MileStole</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(MileStole a, MileStole b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(MileStole entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(MileStole a, MileStole b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public MileStoleColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region MileStoleKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="MileStole"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class MileStoleKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the MileStoleKey class.
		/// </summary>
		public MileStoleKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the MileStoleKey class.
		/// </summary>
		public MileStoleKey(MileStoleBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.MileStoleId = entity.MileStoleId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the MileStoleKey class.
		/// </summary>
		public MileStoleKey(System.Int32 _mileStoleId)
		{
			#region Init Properties

			this.MileStoleId = _mileStoleId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private MileStoleBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public MileStoleBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the MileStoleId property
		private System.Int32 _mileStoleId;
		
		/// <summary>
		/// Gets or sets the MileStoleId property.
		/// </summary>
		public System.Int32 MileStoleId
		{
			get { return _mileStoleId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.MileStoleId = value;
				
				_mileStoleId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				MileStoleId = ( values["MileStoleId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["MileStoleId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("MileStoleId", MileStoleId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("MileStoleId: {0}{1}",
								MileStoleId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region MileStoleColumn Enum
	
	/// <summary>
	/// Enumerate the MileStole columns.
	/// </summary>
	[Serializable]
	public enum MileStoleColumn : int
	{
		/// <summary>
		/// MileStoleId : 
		/// </summary>
		[EnumTextValue("MileStoleID")]
		[ColumnEnum("MileStoleID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		MileStoleId = 1,
		/// <summary>
		/// MileStoleName : 
		/// </summary>
		[EnumTextValue("MileStoleName")]
		[ColumnEnum("MileStoleName", typeof(System.String), System.Data.DbType.String, false, false, true, 1000)]
		MileStoleName = 2,
		/// <summary>
		/// OriginalDueDate : 
		/// </summary>
		[EnumTextValue("OriginalDueDate")]
		[ColumnEnum("OriginalDueDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		OriginalDueDate = 3,
		/// <summary>
		/// RevisedDueDate : 
		/// </summary>
		[EnumTextValue("RevisedDueDate")]
		[ColumnEnum("RevisedDueDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		RevisedDueDate = 4,
		/// <summary>
		/// CompleteDate : 
		/// </summary>
		[EnumTextValue("CompleteDate")]
		[ColumnEnum("CompleteDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, true)]
		CompleteDate = 5,
		/// <summary>
		/// Progress : 
		/// </summary>
		[EnumTextValue("Progress")]
		[ColumnEnum("Progress", typeof(System.Double), System.Data.DbType.Double, false, false, true)]
		Progress = 6,
		/// <summary>
		/// ProjectId : 
		/// </summary>
		[EnumTextValue("ProjectID")]
		[ColumnEnum("ProjectID", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		ProjectId = 7,
		/// <summary>
		/// Enabled : 
		/// </summary>
		[EnumTextValue("Enabled")]
		[ColumnEnum("Enabled", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		Enabled = 8,
		/// <summary>
		/// MileStoleOrder : 
		/// </summary>
		[EnumTextValue("MileStoleOrder")]
		[ColumnEnum("MileStoleOrder", typeof(System.Int32), System.Data.DbType.Int32, false, false, true)]
		MileStoleOrder = 9
	}//End enum

	#endregion MileStoleColumn Enum

} // end namespace
