
/*
	File generated by NetTiers templates [www.nettiers.com]
	Important: Do not modify this file. Edit the file Project.cs instead.
*/

#region using directives
using System;
using System.ComponentModel;
using System.Collections;
using System.Xml.Serialization;
using System.Runtime.Serialization;

using Agile.Entities.Validation;
#endregion

namespace Agile.Entities
{
	///<summary>
	/// An object representation of the 'tblProject' table. [No description found the database]	
	///</summary>
	[Serializable]
	[DataObject, CLSCompliant(true)]
	public abstract partial class ProjectBase : EntityBase, IProject, IEntityId<ProjectKey>, System.IComparable, System.ICloneable, ICloneableEx, IEditableObject, IComponent, INotifyPropertyChanged
	{		
		#region Variable Declarations
		
		/// <summary>
		///  Hold the inner data of the entity.
		/// </summary>
		private ProjectEntityData entityData;
		
		/// <summary>
		/// 	Hold the original data of the entity, as loaded from the repository.
		/// </summary>
		private ProjectEntityData _originalData;
		
		/// <summary>
		/// 	Hold a backup of the inner data of the entity.
		/// </summary>
		private ProjectEntityData backupData; 
		
		/// <summary>
		/// 	Key used if Tracking is Enabled for the <see cref="EntityLocator" />.
		/// </summary>
		private string entityTrackingKey;
		
		/// <summary>
		/// 	Hold the parent TList&lt;entity&gt; in which this entity maybe contained.
		/// </summary>
		/// <remark>Mostly used for databinding</remark>
		[NonSerialized]
		private TList<Project> parentCollection;
		
		private bool inTxn = false;
		
		/// <summary>
		/// Occurs when a value is being changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ProjectEventHandler ColumnChanging;		
		
		/// <summary>
		/// Occurs after a value has been changed for the specified column.
		/// </summary>
		[field:NonSerialized]
		public event ProjectEventHandler ColumnChanged;
		
		#endregion Variable Declarations
		
		#region Constructors
		///<summary>
		/// Creates a new <see cref="ProjectBase"/> instance.
		///</summary>
		public ProjectBase()
		{
			this.entityData = new ProjectEntityData();
			this.backupData = null;
		}		
		
		///<summary>
		/// Creates a new <see cref="ProjectBase"/> instance.
		///</summary>
		///<param name="_projectName"></param>
		///<param name="_startDate"></param>
		///<param name="_deadline"></param>
		///<param name="_description"></param>
		///<param name="_active"></param>
		public ProjectBase(System.String _projectName, System.DateTime _startDate, System.DateTime _deadline, 
			System.String _description, System.Boolean? _active)
		{
			this.entityData = new ProjectEntityData();
			this.backupData = null;

			this.ProjectName = _projectName;
			this.StartDate = _startDate;
			this.Deadline = _deadline;
			this.Description = _description;
			this.Active = _active;
		}
		
		///<summary>
		/// A simple factory method to create a new <see cref="Project"/> instance.
		///</summary>
		///<param name="_projectName"></param>
		///<param name="_startDate"></param>
		///<param name="_deadline"></param>
		///<param name="_description"></param>
		///<param name="_active"></param>
		public static Project CreateProject(System.String _projectName, System.DateTime _startDate, System.DateTime _deadline, 
			System.String _description, System.Boolean? _active)
		{
			Project newProject = new Project();
			newProject.ProjectName = _projectName;
			newProject.StartDate = _startDate;
			newProject.Deadline = _deadline;
			newProject.Description = _description;
			newProject.Active = _active;
			return newProject;
		}
				
		#endregion Constructors
			
		#region Properties	
		
		#region Data Properties		
		/// <summary>
		/// 	Gets or sets the ProjectId property. 
		///		
		/// </summary>
		/// <value>This type is int.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[ReadOnlyAttribute(false)/*, XmlIgnoreAttribute()*/, DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(true, true, false)]
		public virtual System.Int32 ProjectId
		{
			get
			{
				return this.entityData.ProjectId; 
			}
			
			set
			{
				if (this.entityData.ProjectId == value)
					return;
					
				OnColumnChanging(ProjectColumn.ProjectId, this.entityData.ProjectId);
				this.entityData.ProjectId = value;
				this.EntityId.ProjectId = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ProjectColumn.ProjectId, this.entityData.ProjectId);
				OnPropertyChanged("ProjectId");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the ProjectName property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 255)]
		public virtual System.String ProjectName
		{
			get
			{
				return this.entityData.ProjectName; 
			}
			
			set
			{
				if (this.entityData.ProjectName == value)
					return;
					
				OnColumnChanging(ProjectColumn.ProjectName, this.entityData.ProjectName);
				this.entityData.ProjectName = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ProjectColumn.ProjectName, this.entityData.ProjectName);
				OnPropertyChanged("ProjectName");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the StartDate property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime StartDate
		{
			get
			{
				return this.entityData.StartDate; 
			}
			
			set
			{
				if (this.entityData.StartDate == value)
					return;
					
				OnColumnChanging(ProjectColumn.StartDate, this.entityData.StartDate);
				this.entityData.StartDate = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ProjectColumn.StartDate, this.entityData.StartDate);
				OnPropertyChanged("StartDate");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Deadline property. 
		///		
		/// </summary>
		/// <value>This type is datetime.</value>
		/// <remarks>
		/// This property can not be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, false)]
		public virtual System.DateTime Deadline
		{
			get
			{
				return this.entityData.Deadline; 
			}
			
			set
			{
				if (this.entityData.Deadline == value)
					return;
					
				OnColumnChanging(ProjectColumn.Deadline, this.entityData.Deadline);
				this.entityData.Deadline = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ProjectColumn.Deadline, this.entityData.Deadline);
				OnPropertyChanged("Deadline");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Description property. 
		///		
		/// </summary>
		/// <value>This type is nvarchar.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true, 400)]
		public virtual System.String Description
		{
			get
			{
				return this.entityData.Description; 
			}
			
			set
			{
				if (this.entityData.Description == value)
					return;
					
				OnColumnChanging(ProjectColumn.Description, this.entityData.Description);
				this.entityData.Description = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ProjectColumn.Description, this.entityData.Description);
				OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// 	Gets or sets the Active property. 
		///		
		/// </summary>
		/// <value>This type is bit.</value>
		/// <remarks>
		/// This property can be set to null. 
		/// If this column is null, this property will return false. It is up to the developer
		/// to check the value of IsActiveNull() and perform business logic appropriately.
		/// </remarks>




		[DescriptionAttribute(@""), System.ComponentModel.Bindable( System.ComponentModel.BindableSupport.Yes)]
		[DataObjectField(false, false, true)]
		public virtual System.Boolean? Active
		{
			get
			{
				return this.entityData.Active; 
			}
			
			set
			{
				if (this.entityData.Active == value)
					return;
					
				OnColumnChanging(ProjectColumn.Active, this.entityData.Active);
				this.entityData.Active = value;
				if (this.EntityState == EntityState.Unchanged)
					this.EntityState = EntityState.Changed;
				OnColumnChanged(ProjectColumn.Active, this.entityData.Active);
				OnPropertyChanged("Active");
			}
		}
		
		#endregion Data Properties		

		#region Source Foreign Key Property
				
		#endregion
		
		#region Children Collections
	
		/// <summary>
		///	Holds a collection of DieRequest objects
		///	which are related to this object through the relation FK_tblDIERequest_tblProject
		/// </summary>	
		[System.ComponentModel.Bindable(System.ComponentModel.BindableSupport.Yes)]
		public virtual TList<DieRequest> DieRequestCollection
		{
			get { return entityData.DieRequestCollection; }
			set { entityData.DieRequestCollection = value; }	
		}
		#endregion Children Collections
		
		#endregion
		#region Validation
		
		/// <summary>
		/// Assigns validation rules to this object based on model definition.
		/// </summary>
		/// <remarks>This method overrides the base class to add schema related validation.</remarks>
		protected override void AddValidationRules()
		{
			//Validation rules based on database schema.
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("ProjectName", "Project Name", 255));
			ValidationRules.AddRule( CommonRules.StringMaxLength, 
				new CommonRules.MaxLengthRuleArgs("Description", "Description", 400));
		}
   		#endregion
		
		#region Table Meta Data
		/// <summary>
		///		The name of the underlying database table.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string TableName
		{
			get { return "tblProject"; }
		}
		
		/// <summary>
		///		The name of the underlying database table's columns.
		/// </summary>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public override string[] TableColumns
		{
			get
			{
				return new string[] {"ProjectID", "ProjectName", "StartDate", "Deadline", "Description", "Active"};
			}
		}
		#endregion 
		
		#region IEditableObject
		
		#region  CancelAddNew Event
		/// <summary>
        /// The delegate for the CancelAddNew event.
        /// </summary>
        /// <param name="sender"></param>
        /// <param name="e"></param>
		public delegate void CancelAddNewEventHandler(object sender, EventArgs e);
    
    	/// <summary>
		/// The CancelAddNew event.
		/// </summary>
		[field:NonSerialized]
		public event CancelAddNewEventHandler CancelAddNew ;

		/// <summary>
        /// Called when [cancel add new].
        /// </summary>
        public void OnCancelAddNew()
        {    
			if (!SuppressEntityEvents)
			{
	            CancelAddNewEventHandler handler = CancelAddNew ;
            	if (handler != null)
	            {    
    	            handler(this, EventArgs.Empty) ;
        	    }
	        }
        }
		#endregion 
		
		/// <summary>
		/// Begins an edit on an object.
		/// </summary>
		void IEditableObject.BeginEdit() 
	    {
	        //Console.WriteLine("Start BeginEdit");
	        if (!inTxn) 
	        {
	            this.backupData = this.entityData.Clone() as ProjectEntityData;
	            inTxn = true;
	            //Console.WriteLine("BeginEdit");
	        }
	        //Console.WriteLine("End BeginEdit");
	    }
	
		/// <summary>
		/// Discards changes since the last <c>BeginEdit</c> call.
		/// </summary>
	    void IEditableObject.CancelEdit() 
	    {
	        //Console.WriteLine("Start CancelEdit");
	        if (this.inTxn) 
	        {
	            this.entityData = this.backupData;
	            this.backupData = null;
				this.inTxn = false;

				if (this.bindingIsNew)
	        	//if (this.EntityState == EntityState.Added)
	        	{
					if (this.parentCollection != null)
						this.parentCollection.Remove( (Project) this ) ;
				}	            
	        }
	        //Console.WriteLine("End CancelEdit");
	    }
	
		/// <summary>
		/// Pushes changes since the last <c>BeginEdit</c> or <c>IBindingList.AddNew</c> call into the underlying object.
		/// </summary>
	    void IEditableObject.EndEdit() 
	    {
	        //Console.WriteLine("Start EndEdit" + this.custData.id + this.custData.lastName);
	        if (this.inTxn) 
	        {
	            this.backupData = null;
				if (this.IsDirty) 
				{
					if (this.bindingIsNew) {
						this.EntityState = EntityState.Added;
						this.bindingIsNew = false ;
					}
					else
						if (this.EntityState == EntityState.Unchanged) 
							this.EntityState = EntityState.Changed ;
				}

				this.bindingIsNew = false ;
	            this.inTxn = false;	            
	        }
	        //Console.WriteLine("End EndEdit");
	    }
	    
	    /// <summary>
        /// Gets or sets the parent collection of this current entity, if available.
        /// </summary>
        /// <value>The parent collection.</value>
	    [XmlIgnore]
		[Browsable(false)]
	    public override object ParentCollection
	    {
	        get 
	        {
	            return this.parentCollection;
	        }
	        set 
	        {
	            this.parentCollection = value as TList<Project>;
	        }
	    }
	    
	    /// <summary>
        /// Called when the entity is changed.
        /// </summary>
	    private void OnEntityChanged() 
	    {
	        if (!SuppressEntityEvents && !inTxn && this.parentCollection != null) 
	        {
	            this.parentCollection.EntityChanged(this as Project);
	        }
	    }


		#endregion
		
		#region ICloneable Members
		///<summary>
		///  Returns a Typed Project Entity 
		///</summary>
		protected virtual Project Copy(IDictionary existingCopies)
		{
			if (existingCopies == null)
			{
				// This is the root of the tree to be copied!
				existingCopies = new Hashtable();
			}

			//shallow copy entity
			Project copy = new Project();
			existingCopies.Add(this, copy);
			copy.SuppressEntityEvents = true;
				copy.ProjectId = this.ProjectId;
				copy.ProjectName = this.ProjectName;
				copy.StartDate = this.StartDate;
				copy.Deadline = this.Deadline;
				copy.Description = this.Description;
				copy.Active = this.Active;
			
		
			//deep copy nested objects
			copy.DieRequestCollection = (TList<DieRequest>) MakeCopyOf(this.DieRequestCollection, existingCopies); 
			copy.EntityState = this.EntityState;
			copy.SuppressEntityEvents = false;
			return copy;
		}		
		
		
		
		///<summary>
		///  Returns a Typed Project Entity 
		///</summary>
		public virtual Project Copy()
		{
			return this.Copy(null);	
		}
		
		///<summary>
		/// ICloneable.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone()
		{
			return this.Copy(null);
		}
		
		///<summary>
		/// ICloneableEx.Clone() Member, returns the Shallow Copy of this entity.
		///</summary>
		public object Clone(IDictionary existingCopies)
		{
			return this.Copy(existingCopies);
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x)
		{
			if (x == null)
				return null;
				
			if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable Interface.");
		}
		
		///<summary>
		/// Returns a deep copy of the child collection object passed in.
		///</summary>
		public static object MakeCopyOf(object x, IDictionary existingCopies)
		{
			if (x == null)
				return null;
			
			if (x is ICloneableEx)
			{
				// Return a deep copy of the object
				return ((ICloneableEx)x).Clone(existingCopies);
			}
			else if (x is ICloneable)
			{
				// Return a deep copy of the object
				return ((ICloneable)x).Clone();
			}
			else
				throw new System.NotSupportedException("Object Does Not Implement the ICloneable or IClonableEx Interface.");
		}
		
		
		///<summary>
		///  Returns a Typed Project Entity which is a deep copy of the current entity.
		///</summary>
		public virtual Project DeepCopy()
		{
			return EntityHelper.Clone<Project>(this as Project);	
		}
		#endregion
		
		#region Methods	
			
		///<summary>
		/// Revert all changes and restore original values.
		///</summary>
		public override void CancelChanges()
		{
			IEditableObject obj = (IEditableObject) this;
			obj.CancelEdit();

			this.entityData = null;
			if (this._originalData != null)
			{
				this.entityData = this._originalData.Clone() as ProjectEntityData;
			}
			else
			{
				//Since this had no _originalData, then just reset the entityData with a new one.  entityData cannot be null.
				this.entityData = new ProjectEntityData();
			}
		}	
		
		/// <summary>
		/// Accepts the changes made to this object.
		/// </summary>
		/// <remarks>
		/// After calling this method, properties: IsDirty, IsNew are false. IsDeleted flag remains unchanged as it is handled by the parent List.
		/// </remarks>
		public override void AcceptChanges()
		{
			base.AcceptChanges();

			// we keep of the original version of the data
			this._originalData = null;
			this._originalData = this.entityData.Clone() as ProjectEntityData;
		}
		
		#region Comparision with original data
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="column">The column.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool IsPropertyChanged(ProjectColumn column)
		{
			switch(column)
			{
					case ProjectColumn.ProjectId:
					return entityData.ProjectId != _originalData.ProjectId;
					case ProjectColumn.ProjectName:
					return entityData.ProjectName != _originalData.ProjectName;
					case ProjectColumn.StartDate:
					return entityData.StartDate != _originalData.StartDate;
					case ProjectColumn.Deadline:
					return entityData.Deadline != _originalData.Deadline;
					case ProjectColumn.Description:
					return entityData.Description != _originalData.Description;
					case ProjectColumn.Active:
					return entityData.Active != _originalData.Active;
			
				default:
					return false;
			}
		}
		
		/// <summary>
		/// Determines whether the property value has changed from the original data.
		/// </summary>
		/// <param name="columnName">The column name.</param>
		/// <returns>
		/// 	<c>true</c> if the property value has changed; otherwise, <c>false</c>.
		/// </returns>
		public override bool IsPropertyChanged(string columnName)
		{
			return 	IsPropertyChanged(EntityHelper.GetEnumValue< ProjectColumn >(columnName));
		}
		
		/// <summary>
		/// Determines whether the data has changed from original.
		/// </summary>
		/// <returns>
		/// 	<c>true</c> if data has changed; otherwise, <c>false</c>.
		/// </returns>
		public bool HasDataChanged()
		{
			bool result = false;
			result = result || entityData.ProjectId != _originalData.ProjectId;
			result = result || entityData.ProjectName != _originalData.ProjectName;
			result = result || entityData.StartDate != _originalData.StartDate;
			result = result || entityData.Deadline != _originalData.Deadline;
			result = result || entityData.Description != _originalData.Description;
			result = result || entityData.Active != _originalData.Active;
			return result;
		}	
		
		///<summary>
		///  Returns a Project Entity with the original data.
		///</summary>
		public Project GetOriginalEntity()
		{
			if (_originalData != null)
				return CreateProject(
				_originalData.ProjectName,
				_originalData.StartDate,
				_originalData.Deadline,
				_originalData.Description,
				_originalData.Active
				);
				
			return (Project)this.Clone();
		}
		#endregion
	
	#region Value Semantics Instance Equality
        ///<summary>
        /// Returns a value indicating whether this instance is equal to a specified object using value semantics.
        ///</summary>
        ///<param name="Object1">An object to compare to this instance.</param>
        ///<returns>true if Object1 is a <see cref="ProjectBase"/> and has the same value as this instance; otherwise, false.</returns>
        public override bool Equals(object Object1)
        {
			// Cast exception if Object1 is null or DbNull
			if (Object1 != null && Object1 != DBNull.Value && Object1 is ProjectBase)
				return ValueEquals(this, (ProjectBase)Object1);
			else
				return false;
        }

        /// <summary>
		/// Serves as a hash function for a particular type, suitable for use in hashing algorithms and data structures like a hash table.
        /// Provides a hash function that is appropriate for <see cref="ProjectBase"/> class 
        /// and that ensures a better distribution in the hash table
        /// </summary>
        /// <returns>number (hash code) that corresponds to the value of an object</returns>
        public override int GetHashCode()
        {
			return this.ProjectId.GetHashCode() ^ 
					((this.ProjectName == null) ? string.Empty : this.ProjectName.ToString()).GetHashCode() ^ 
					this.StartDate.GetHashCode() ^ 
					this.Deadline.GetHashCode() ^ 
					((this.Description == null) ? string.Empty : this.Description.ToString()).GetHashCode() ^ 
					((this.Active == null) ? string.Empty : this.Active.ToString()).GetHashCode();
        }
		
		///<summary>
		/// Returns a value indicating whether this instance is equal to a specified object using value semantics.
		///</summary>
		///<param name="toObject">An object to compare to this instance.</param>
		///<returns>true if toObject is a <see cref="ProjectBase"/> and has the same value as this instance; otherwise, false.</returns>
		public virtual bool Equals(ProjectBase toObject)
		{
			if (toObject == null)
				return false;
			return ValueEquals(this, toObject);
		}
		#endregion
		
		///<summary>
		/// Determines whether the specified <see cref="ProjectBase"/> instances are considered equal using value semantics.
		///</summary>
		///<param name="Object1">The first <see cref="ProjectBase"/> to compare.</param>
		///<param name="Object2">The second <see cref="ProjectBase"/> to compare. </param>
		///<returns>true if Object1 is the same instance as Object2 or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
		public static bool ValueEquals(ProjectBase Object1, ProjectBase Object2)
		{
			// both are null
			if (Object1 == null && Object2 == null)
				return true;

			// one or the other is null, but not both
			if (Object1 == null ^ Object2 == null)
				return false;
				
			bool equal = true;
			if (Object1.ProjectId != Object2.ProjectId)
				equal = false;
			if ( Object1.ProjectName != null && Object2.ProjectName != null )
			{
				if (Object1.ProjectName != Object2.ProjectName)
					equal = false;
			}
			else if (Object1.ProjectName == null ^ Object2.ProjectName == null )
			{
				equal = false;
			}
			if (Object1.StartDate != Object2.StartDate)
				equal = false;
			if (Object1.Deadline != Object2.Deadline)
				equal = false;
			if ( Object1.Description != null && Object2.Description != null )
			{
				if (Object1.Description != Object2.Description)
					equal = false;
			}
			else if (Object1.Description == null ^ Object2.Description == null )
			{
				equal = false;
			}
			if ( Object1.Active != null && Object2.Active != null )
			{
				if (Object1.Active != Object2.Active)
					equal = false;
			}
			else if (Object1.Active == null ^ Object2.Active == null )
			{
				equal = false;
			}
					
			return equal;
		}
		
		#endregion
		
		#region IComparable Members
		///<summary>
		/// Compares this instance to a specified object and returns an indication of their relative values.
		///<param name="obj">An object to compare to this instance, or a null reference (Nothing in Visual Basic).</param>
		///</summary>
		///<returns>A signed integer that indicates the relative order of this instance and obj.</returns>
		public virtual int CompareTo(object obj)
		{
			throw new NotImplementedException();
			//return this. GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]) .CompareTo(((ProjectBase)obj).GetPropertyName(SourceTable.PrimaryKey.MemberColumns[0]));
		}
		
		/*
		// static method to get a Comparer object
        public static ProjectComparer GetComparer()
        {
            return new ProjectComparer();
        }
        */

        // Comparer delegates back to Project
        // Employee uses the integer's default
        // CompareTo method
        /*
        public int CompareTo(Item rhs)
        {
            return this.Id.CompareTo(rhs.Id);
        }
        */

/*
        // Special implementation to be called by custom comparer
        public int CompareTo(Project rhs, ProjectColumn which)
        {
            switch (which)
            {
            	
            	
            	case ProjectColumn.ProjectId:
            		return this.ProjectId.CompareTo(rhs.ProjectId);
            		
            		                 
            	
            	
            	case ProjectColumn.ProjectName:
            		return this.ProjectName.CompareTo(rhs.ProjectName);
            		
            		                 
            	
            	
            	case ProjectColumn.StartDate:
            		return this.StartDate.CompareTo(rhs.StartDate);
            		
            		                 
            	
            	
            	case ProjectColumn.Deadline:
            		return this.Deadline.CompareTo(rhs.Deadline);
            		
            		                 
            	
            	
            	case ProjectColumn.Description:
            		return this.Description.CompareTo(rhs.Description);
            		
            		                 
            	
            	
            	case ProjectColumn.Active:
            		return this.Active.Value.CompareTo(rhs.Active.Value);
            		
            		                 
            }
            return 0;
        }
        */
	
		#endregion
		
		#region IComponent Members
		
		private ISite _site = null;

		/// <summary>
		/// Gets or Sets the site where this data is located.
		/// </summary>
		[XmlIgnore]
		[SoapIgnore]
		[Browsable(false)]
		public ISite Site
		{
			get{ return this._site; }
			set{ this._site = value; }
		}

		#endregion

		#region IDisposable Members
		
		/// <summary>
		/// Notify those that care when we dispose.
		/// </summary>
		[field:NonSerialized]
		public event System.EventHandler Disposed;

		/// <summary>
		/// Clean up. Nothing here though.
		/// </summary>
		public virtual void Dispose()
		{
			this.parentCollection = null;
			this.Dispose(true);
			GC.SuppressFinalize(this);
		}
		
		/// <summary>
		/// Clean up.
		/// </summary>
		protected virtual void Dispose(bool disposing)
		{
			if (disposing)
			{
				EventHandler handler = Disposed;
				if (handler != null)
					handler(this, EventArgs.Empty);
			}
		}
		
		#endregion
				
		#region IEntityKey<ProjectKey> Members
		
		// member variable for the EntityId property
		private ProjectKey _entityId;

		/// <summary>
		/// Gets or sets the EntityId property.
		/// </summary>
		[XmlIgnore]
		public virtual ProjectKey EntityId
		{
			get
			{
				if ( _entityId == null )
				{
					_entityId = new ProjectKey(this);
				}

				return _entityId;
			}
			set
			{
				if ( value != null )
				{
					value.Entity = this;
				}
				
				_entityId = value;
			}
		}
		
		#endregion
		
		#region EntityState
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false) , XmlIgnoreAttribute()]
		public override EntityState EntityState 
		{ 
			get{ return entityData.EntityState;	 } 
			set{ entityData.EntityState = value; } 
		}
		#endregion 
		
		#region EntityTrackingKey
		///<summary>
		/// Provides the tracking key for the <see cref="EntityLocator"/>
		///</summary>
		[XmlIgnore]
		public override string EntityTrackingKey
		{
			get
			{
				if(entityTrackingKey == null)
					entityTrackingKey = new System.Text.StringBuilder("Project")
					.Append("|").Append( this.ProjectId.ToString()).ToString();
				return entityTrackingKey;
			}
			set
		    {
		        if (value != null)
                    entityTrackingKey = value;
		    }
		}
		#endregion 
		
		#region ToString Method
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return string.Format(System.Globalization.CultureInfo.InvariantCulture,
				"{7}{6}- ProjectId: {0}{6}- ProjectName: {1}{6}- StartDate: {2}{6}- Deadline: {3}{6}- Description: {4}{6}- Active: {5}{6}{8}", 
				this.ProjectId,
				(this.ProjectName == null) ? string.Empty : this.ProjectName.ToString(),
				this.StartDate,
				this.Deadline,
				(this.Description == null) ? string.Empty : this.Description.ToString(),
				(this.Active == null) ? string.Empty : this.Active.ToString(),
				System.Environment.NewLine, 
				this.GetType(),
				this.Error.Length == 0 ? string.Empty : string.Format("- Error: {0}\n",this.Error));
		}
		
		#endregion ToString Method
		
		#region Inner data class
		
	/// <summary>
	///		The data structure representation of the 'tblProject' table.
	/// </summary>
	/// <remarks>
	/// 	This struct is generated by a tool and should never be modified.
	/// </remarks>
	[EditorBrowsable(EditorBrowsableState.Never)]
	[Serializable]
	internal protected class ProjectEntityData : ICloneable, ICloneableEx
	{
		#region Variable Declarations
		private EntityState currentEntityState = EntityState.Added;
		
		#region Primary key(s)
		/// <summary>			
		/// ProjectID : 
		/// </summary>
		/// <remarks>Member of the primary key of the underlying table "tblProject"</remarks>
		public System.Int32 ProjectId;
			
		#endregion
		
		#region Non Primary key(s)
		
		
		/// <summary>
		/// ProjectName : 
		/// </summary>
		public System.String		  ProjectName = null;
		
		/// <summary>
		/// StartDate : 
		/// </summary>
		public System.DateTime		  StartDate = DateTime.MinValue;
		
		/// <summary>
		/// Deadline : 
		/// </summary>
		public System.DateTime		  Deadline = DateTime.MinValue;
		
		/// <summary>
		/// Description : 
		/// </summary>
		public System.String		  Description = null;
		
		/// <summary>
		/// Active : 
		/// </summary>
		public System.Boolean?		  Active = null;
		#endregion
			
		#region Source Foreign Key Property
				
		#endregion
		#endregion Variable Declarations
	
		#region Data Properties

		#region DieRequestCollection
		
		private TList<DieRequest> _dieRequestProjectId;
		
		/// <summary>
		///	Holds a collection of entity objects
		///	which are related to this object through the relation _dieRequestProjectId
		/// </summary>
		
		public TList<DieRequest> DieRequestCollection
		{
			get
			{
				if (_dieRequestProjectId == null)
				{
				_dieRequestProjectId = new TList<DieRequest>();
				}
	
				return _dieRequestProjectId;
			}
			set { _dieRequestProjectId = value; }
		}
		
		#endregion

		#endregion Data Properties
		
		#region Clone Method

		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public Object Clone()
		{
			ProjectEntityData _tmp = new ProjectEntityData();
						
			_tmp.ProjectId = this.ProjectId;
			
			_tmp.ProjectName = this.ProjectName;
			_tmp.StartDate = this.StartDate;
			_tmp.Deadline = this.Deadline;
			_tmp.Description = this.Description;
			_tmp.Active = this.Active;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			if (this._dieRequestProjectId != null)
				_tmp.DieRequestCollection = (TList<DieRequest>) MakeCopyOf(this.DieRequestCollection); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		/// <summary>
		/// Creates a new object that is a copy of the current instance.
		/// </summary>
		/// <returns>A new object that is a copy of this instance.</returns>
		public object Clone(IDictionary existingCopies)
		{
			if (existingCopies == null)
				existingCopies = new Hashtable();
				
			ProjectEntityData _tmp = new ProjectEntityData();
						
			_tmp.ProjectId = this.ProjectId;
			
			_tmp.ProjectName = this.ProjectName;
			_tmp.StartDate = this.StartDate;
			_tmp.Deadline = this.Deadline;
			_tmp.Description = this.Description;
			_tmp.Active = this.Active;
			
			#region Source Parent Composite Entities
			#endregion
		
			#region Child Collections
			//deep copy nested objects
			_tmp.DieRequestCollection = (TList<DieRequest>) MakeCopyOf(this.DieRequestCollection, existingCopies); 
			#endregion Child Collections
			
			//EntityState
			_tmp.EntityState = this.EntityState;
			
			return _tmp;
		}
		
		#endregion Clone Method
		
		/// <summary>
		///		Indicates state of object
		/// </summary>
		/// <remarks>0=Unchanged, 1=Added, 2=Changed</remarks>
		[BrowsableAttribute(false), XmlIgnoreAttribute()]
		public EntityState	EntityState
		{
			get { return currentEntityState;  }
			set { currentEntityState = value; }
		}
	
	}//End struct











		#endregion
		
				
		
		#region Events trigger
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ProjectColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanging(ProjectColumn column)
		{
			OnColumnChanging(column, null);
			return;
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ProjectColumn"/> which has raised the event.</param>
		public virtual void OnColumnChanged(ProjectColumn column)
		{
			OnColumnChanged(column, null);
			return;
		} 
		
		
		/// <summary>
		/// Raises the <see cref="ColumnChanging" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ProjectColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanging(ProjectColumn column, object value)
		{
			if(IsEntityTracked && EntityState != EntityState.Added && !EntityManager.TrackChangedEntities)
				EntityManager.StopTracking(entityTrackingKey);
				
			if (!SuppressEntityEvents)
			{
				ProjectEventHandler handler = ColumnChanging;
				if(handler != null)
				{
					handler(this, new ProjectEventArgs(column, value));
				}
			}
		}
		
		/// <summary>
		/// Raises the <see cref="ColumnChanged" /> event.
		/// </summary>
		/// <param name="column">The <see cref="ProjectColumn"/> which has raised the event.</param>
		/// <param name="value">The changed value.</param>
		public virtual void OnColumnChanged(ProjectColumn column, object value)
		{
			if (!SuppressEntityEvents)
			{
				ProjectEventHandler handler = ColumnChanged;
				if(handler != null)
				{
					handler(this, new ProjectEventArgs(column, value));
				}
			
				// warn the parent list that i have changed
				OnEntityChanged();
			}
		} 
		#endregion
			
	} // End Class
	
	
	#region ProjectEventArgs class
	/// <summary>
	/// Provides data for the ColumnChanging and ColumnChanged events.
	/// </summary>
	/// <remarks>
	/// The ColumnChanging and ColumnChanged events occur when a change is made to the value 
	/// of a property of a <see cref="Project"/> object.
	/// </remarks>
	public class ProjectEventArgs : System.EventArgs
	{
		private ProjectColumn column;
		private object value;
		
		///<summary>
		/// Initalizes a new Instance of the ProjectEventArgs class.
		///</summary>
		public ProjectEventArgs(ProjectColumn column)
		{
			this.column = column;
		}
		
		///<summary>
		/// Initalizes a new Instance of the ProjectEventArgs class.
		///</summary>
		public ProjectEventArgs(ProjectColumn column, object value)
		{
			this.column = column;
			this.value = value;
		}
		
		///<summary>
		/// The ProjectColumn that was modified, which has raised the event.
		///</summary>
		///<value cref="ProjectColumn" />
		public ProjectColumn Column { get { return this.column; } }
		
		/// <summary>
        /// Gets the current value of the column.
        /// </summary>
        /// <value>The current value of the column.</value>
		public object Value{ get { return this.value; } }

	}
	#endregion
	
	///<summary>
	/// Define a delegate for all Project related events.
	///</summary>
	public delegate void ProjectEventHandler(object sender, ProjectEventArgs e);
	
	#region ProjectComparer
		
	/// <summary>
	///	Strongly Typed IComparer
	/// </summary>
	public class ProjectComparer : System.Collections.Generic.IComparer<Project>
	{
		ProjectColumn whichComparison;
		
		/// <summary>
        /// Initializes a new instance of the <see cref="T:ProjectComparer"/> class.
        /// </summary>
		public ProjectComparer()
        {            
        }               
        
        /// <summary>
        /// Initializes a new instance of the <see cref="T:ProjectComparer"/> class.
        /// </summary>
        /// <param name="column">The column to sort on.</param>
        public ProjectComparer(ProjectColumn column)
        {
            this.whichComparison = column;
        }

		/// <summary>
        /// Determines whether the specified <c cref="Project"/> instances are considered equal.
        /// </summary>
        /// <param name="a">The first <c cref="Project"/> to compare.</param>
        /// <param name="b">The second <c>Project</c> to compare.</param>
        /// <returns>true if objA is the same instance as objB or if both are null references or if objA.Equals(objB) returns true; otherwise, false.</returns>
        public bool Equals(Project a, Project b)
        {
            return this.Compare(a, b) == 0;
        }

		/// <summary>
        /// Gets the hash code of the specified entity.
        /// </summary>
        /// <param name="entity">The entity.</param>
        /// <returns></returns>
        public int GetHashCode(Project entity)
        {
            return entity.GetHashCode();
        }

        /// <summary>
        /// Performs a case-insensitive comparison of two objects of the same type and returns a value indicating whether one is less than, equal to, or greater than the other.
        /// </summary>
        /// <param name="a">The first object to compare.</param>
        /// <param name="b">The second object to compare.</param>
        /// <returns></returns>
        public int Compare(Project a, Project b)
        {
        	EntityPropertyComparer entityPropertyComparer = new EntityPropertyComparer(this.whichComparison.ToString());
        	return entityPropertyComparer.Compare(a, b);
        }

		/// <summary>
        /// Gets or sets the column that will be used for comparison.
        /// </summary>
        /// <value>The comparison column.</value>
        public ProjectColumn WhichComparison
        {
            get { return this.whichComparison; }
            set { this.whichComparison = value; }
        }
	}
	
	#endregion
	
	#region ProjectKey Class

	/// <summary>
	/// Wraps the unique identifier values for the <see cref="Project"/> object.
	/// </summary>
	[Serializable]
	[CLSCompliant(true)]
	public class ProjectKey : EntityKeyBase
	{
		#region Constructors
		
		/// <summary>
		/// Initializes a new instance of the ProjectKey class.
		/// </summary>
		public ProjectKey()
		{
		}
		
		/// <summary>
		/// Initializes a new instance of the ProjectKey class.
		/// </summary>
		public ProjectKey(ProjectBase entity)
		{
			this.Entity = entity;

			#region Init Properties

			if ( entity != null )
			{
				this.ProjectId = entity.ProjectId;
			}

			#endregion
		}
		
		/// <summary>
		/// Initializes a new instance of the ProjectKey class.
		/// </summary>
		public ProjectKey(System.Int32 _projectId)
		{
			#region Init Properties

			this.ProjectId = _projectId;

			#endregion
		}
		
		#endregion Constructors

		#region Properties
		
		// member variable for the Entity property
		private ProjectBase _entity;
		
		/// <summary>
		/// Gets or sets the Entity property.
		/// </summary>
		public ProjectBase Entity
		{
			get { return _entity; }
			set { _entity = value; }
		}
		
		// member variable for the ProjectId property
		private System.Int32 _projectId;
		
		/// <summary>
		/// Gets or sets the ProjectId property.
		/// </summary>
		public System.Int32 ProjectId
		{
			get { return _projectId; }
			set
			{
				if ( this.Entity != null )
					this.Entity.ProjectId = value;
				
				_projectId = value;
			}
		}
		
		#endregion

		#region Methods
		
		/// <summary>
		/// Reads values from the supplied <see cref="IDictionary"/> object into
		/// properties of the current object.
		/// </summary>
		/// <param name="values">An <see cref="IDictionary"/> instance that contains
		/// the key/value pairs to be used as property values.</param>
		public override void Load(IDictionary values)
		{
			#region Init Properties

			if ( values != null )
			{
				ProjectId = ( values["ProjectId"] != null ) ? (System.Int32) EntityUtil.ChangeType(values["ProjectId"], typeof(System.Int32)) : (int)0;
			}

			#endregion
		}

		/// <summary>
		/// Creates a new <see cref="IDictionary"/> object and populates it
		/// with the property values of the current object.
		/// </summary>
		/// <returns>A collection of name/value pairs.</returns>
		public override IDictionary ToDictionary()
		{
			IDictionary values = new Hashtable();

			#region Init Dictionary

			values.Add("ProjectId", ProjectId);

			#endregion Init Dictionary

			return values;
		}
		
		///<summary>
		/// Returns a String that represents the current object.
		///</summary>
		public override string ToString()
		{
			return String.Format("ProjectId: {0}{1}",
								ProjectId,
								System.Environment.NewLine);
		}

		#endregion Methods
	}
	
	#endregion	

	#region ProjectColumn Enum
	
	/// <summary>
	/// Enumerate the Project columns.
	/// </summary>
	[Serializable]
	public enum ProjectColumn : int
	{
		/// <summary>
		/// ProjectId : 
		/// </summary>
		[EnumTextValue("ProjectID")]
		[ColumnEnum("ProjectID", typeof(System.Int32), System.Data.DbType.Int32, true, true, false)]
		ProjectId = 1,
		/// <summary>
		/// ProjectName : 
		/// </summary>
		[EnumTextValue("ProjectName")]
		[ColumnEnum("ProjectName", typeof(System.String), System.Data.DbType.String, false, false, true, 255)]
		ProjectName = 2,
		/// <summary>
		/// StartDate : 
		/// </summary>
		[EnumTextValue("StartDate")]
		[ColumnEnum("StartDate", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		StartDate = 3,
		/// <summary>
		/// Deadline : 
		/// </summary>
		[EnumTextValue("Deadline")]
		[ColumnEnum("Deadline", typeof(System.DateTime), System.Data.DbType.DateTime, false, false, false)]
		Deadline = 4,
		/// <summary>
		/// Description : 
		/// </summary>
		[EnumTextValue("Description")]
		[ColumnEnum("Description", typeof(System.String), System.Data.DbType.String, false, false, true, 400)]
		Description = 5,
		/// <summary>
		/// Active : 
		/// </summary>
		[EnumTextValue("Active")]
		[ColumnEnum("Active", typeof(System.Boolean), System.Data.DbType.Boolean, false, false, true)]
		Active = 6
	}//End enum

	#endregion ProjectColumn Enum

} // end namespace
